apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-app
  template:
    metadata:
      labels:
        app: final-app
    spec:
      containers:
      - name: final-container
        image: final-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: STUDENT_NAME
          value: "Nidha"